In [55]:
import torch

In [56]:
x= torch.tensor([
    [10,20,30],
    [40,50,60]
])

print(x[0])
print(x[1])

print(x[0,0])
print(x[0,2])
print(x[1,1])

print(x[0].shape)
print(x[0,1].shape)

tensor([10, 20, 30])
tensor([40, 50, 60])
tensor(10)
tensor(30)
tensor(50)
torch.Size([3])
torch.Size([])


In [57]:
x= torch.tensor([
    [10,20,30],
    [40,50,60]
])

print(x[0,-1])
print(x[1,-1])
print(x[0,-2])
print(x[-2,-3])

tensor(30)
tensor(60)
tensor(20)
tensor(10)


In [58]:
x = torch.tensor([10, 20, 30, 40, 50])
print(x)
print(x[1:4])
print(x[:3])
print(x[2:])
print(x[:])
print(x[-1:])
print(x[-4:-1])
print(x[-5:-2])
print(x[::2])
print((x[-4::2]))

tensor([10, 20, 30, 40, 50])
tensor([20, 30, 40])
tensor([10, 20, 30])
tensor([30, 40, 50])
tensor([10, 20, 30, 40, 50])
tensor([50])
tensor([20, 30, 40])
tensor([10, 20, 30])
tensor([10, 30, 50])
tensor([20, 40])


In [59]:
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(x[0:2, :])
print(x[:, 1:3])
print(x[0:2, 1:3])
print(x[1:3,0:2])

tensor([[10, 20, 30],
        [40, 50, 60]])
tensor([[20, 30],
        [50, 60],
        [80, 90]])
tensor([[20, 30],
        [50, 60]])
tensor([[40, 50],
        [70, 80]])


In [60]:
x = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(x[0,1,2]) #x[block, row, column]
print(x[:,0,:])
print(x[0,0,:])
print(x[:,1,:])
print(x[:,:,0])
print(x[1,0,2])

tensor(6)
tensor([[1, 2, 3],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor([[ 4,  5,  6],
        [10, 11, 12]])
tensor([[ 1,  4],
        [ 7, 10]])
tensor(9)


In [61]:
x = torch.tensor([10, 20, 30, 40, 50])

print(x[x>25])

y= torch.tensor([5,12,18,25,31,42])

print(y>20)
print(y[y>20])
print(y[y%2==0])

tensor([30, 40, 50])
tensor([False, False, False,  True,  True,  True])
tensor([25, 31, 42])
tensor([12, 18, 42])


In [62]:
x= torch.tensor([10,20,30,40])

result= torch.where(x>25, x, torch.tensor(0)) #condition, value_if_true, value_if_false

print(result)

y= torch.tensor([5,15,25,35,45])

print(torch.where(y>20,y,0))
print(torch.where(y%2==0,y,-1))

tensor([ 0,  0, 30, 40])
tensor([ 0,  0, 25, 35, 45])
tensor([-1, -1, -1, -1, -1])


In [63]:
x= torch.tensor([10,20,30,40,50])
x[2]= 100
print(x)

x[1:3]=0
print(x)

y= torch.tensor([10,20,30,40,50])
print(y)

y[y>30]=0
print(y)

x= torch.tensor([10,20,30,40,50])

x[0]= 99
print(x)

x[1:3]=0
print(x)

x[x>40]=-1
print(x)

tensor([ 10,  20, 100,  40,  50])
tensor([10,  0,  0, 40, 50])
tensor([10, 20, 30, 40, 50])
tensor([10, 20, 30,  0,  0])
tensor([99, 20, 30, 40, 50])
tensor([99,  0,  0, 40, 50])
tensor([-1,  0,  0, 40, -1])


In [64]:
x = torch.zeros(2, 3, 4, 5)
print(x[:,:,:,0], '\n')
print(x[...,0]) #... will cover all required dimentions

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) 

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [65]:
x = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(x[:,:,0])
print(x[...,0])

print(
    x[...,1],
    x[:,:,1],
    torch.equal(x[...,1], x[:,:,1]),
    sep='\n'
)

tensor([[ 1,  4],
        [ 7, 10]])
tensor([[ 1,  4],
        [ 7, 10]])
tensor([[ 2,  5],
        [ 8, 11]])
tensor([[ 2,  5],
        [ 8, 11]])
True
