In [1]:
import numpy as np
import torch

In [2]:
arr= np.array([1,2,3])
x= torch.from_numpy(arr)

print(
    arr,
    x,
    type(arr),
    type(x),
    sep='\n'
)

[1 2 3]
tensor([1, 2, 3])
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [5]:
arr= np.array([1,2,3])
x= torch.from_numpy(arr)

arr[0]=100
x[1]=200

print(
    arr,
    x,
    sep='\n'
)

[100 200   3]
tensor([100, 200,   3])


In [9]:
x= torch.tensor([10,20,30])

arr= x.numpy()

arr[0]=99
x[1]=100

print(
    x,
    arr,
    type(x),
    type(arr),
    sep='\n'
)

tensor([ 99, 100,  30])
[ 99 100  30]
<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [ ]:
arr= np.array([1,2,3])

x=torch.tensor(arr) #just a copy
x1= torch.from_numpy(arr) #shared memory

x[0]=99
x1[1]=100

print(
    arr,
    x,
    x1,
    sep='\n'
)

[  1 100   3]
tensor([99,  2,  3])
tensor([  1, 100,   3])
