In [1]:
import torch

In [6]:
x = torch.tensor([10, 20, 30])
y = torch.tensor([1, 2, 3])

print(x + y)
print(torch.add(x, y))

print(x-y)
print(torch.sub(x, y))

print(x * y)
print(torch.mul(x, y))

print(x/y)
torch.div(x, y)

tensor([11, 22, 33])
tensor([11, 22, 33])
tensor([ 9, 18, 27])
tensor([ 9, 18, 27])
tensor([10, 40, 90])
tensor([10, 40, 90])
tensor([10., 10., 10.])


tensor([10., 10., 10.])

In [7]:
x = torch.tensor([2, 3, 4])

print(x ** 2)
print(torch.pow(x,2))

tensor([ 4,  9, 16])
tensor([ 4,  9, 16])


In [13]:
x = torch.tensor([10, 20, 30])

print(x.sum())
print(torch.sum(x))

y = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(y.sum(dim=0))
print(torch.sum(y,dim=0))

tensor(60)
tensor(60)
tensor([5, 7, 9])
tensor([5, 7, 9])


In [23]:
x = torch.tensor([10, 20, 30])

print(x.float().mean())

y = torch.tensor([10, 20, 30, 40])

print(y.float().mean())
print(torch.mean(y.float()))

x = torch.tensor([10, 30, 5, 20, 15])

print(x.min())
print(x.max())

y = torch.tensor([
    [10, 20, 30],
    [40, 5, 60]
])

print(y.min(dim=0))
print(y.min(dim=1))

x = torch.tensor([15, 3, 27, 8, 20])

print(x.min())
print(x.max())
print(x.argmin())
print(x.argmax())

tensor(20.)
tensor(25.)
tensor(25.)
tensor(5)
tensor(30)
torch.return_types.min(
values=tensor([10,  5, 30]),
indices=tensor([0, 1, 0]))
torch.return_types.min(
values=tensor([10,  5]),
indices=tensor([0, 1]))
tensor(3)
tensor(27)
tensor(1)
tensor(2)


In [27]:
x = torch.tensor([
    [10, 20, 30],
    [40, 5, 60]
])

print(x.min())
print(x.argmin())

print(x.max(dim=0))
print(x.argmax(dim=0))

result= x.min(dim=0)

print(result.values)
print(result.indices)

tensor(5)
tensor(4)
torch.return_types.max(
values=tensor([40, 20, 60]),
indices=tensor([1, 0, 1]))
tensor([1, 0, 1])
tensor([10,  5, 30])
tensor([0, 1, 0])


In [31]:
x = torch.tensor([-10, -5, 0, 5, 10])

print(torch.abs(x)) #abs give absolute values

y = torch.tensor([-20, 7, -3, 0, 15])

print(y.abs())
print(torch.abs(y))

tensor([10,  5,  0,  5, 10])
tensor([20,  7,  3,  0, 15])
tensor([20,  7,  3,  0, 15])


In [33]:
x = torch.tensor([4, 9, 16])

print(torch.sqrt(x))

x = torch.tensor([1.0, 25.0, 36.0, 49.0])

print(torch.sqrt(x))
print(x.sqrt())

tensor([2., 3., 4.])
tensor([1., 5., 6., 7.])
tensor([1., 5., 6., 7.])


In [36]:
x = torch.tensor([0.0, 1.0, 2.0])
print(torch.exp(x)) #exp gives e^x

y = torch.tensor([1.0, 2.7183, 7.3891])
print(torch.log(y)) #gives ln(y)

x = torch.tensor([1.0, 4.0, 9.0, 16.0])

print("sqrt:", torch.sqrt(x))
print("exp:", torch.exp(x))
print("log:", torch.log(x))

tensor([1.0000, 2.7183, 7.3891])
tensor([0.0000, 1.0000, 2.0000])
sqrt: tensor([1., 2., 3., 4.])
exp: tensor([2.7183e+00, 5.4598e+01, 8.1031e+03, 8.8861e+06])
log: tensor([0.0000, 1.3863, 2.1972, 2.7726])


In [37]:
x = torch.tensor([1.2, 2.5, 3.7, -1.2, -1.8])

print(torch.round(x)) #round values
print(torch.floor(x)) #gives nearest lesser integer
print(torch.ceil(x)) #gives nearest greater integer

tensor([ 1.,  2.,  4., -1., -2.])
tensor([ 1.,  2.,  3., -2., -2.])
tensor([ 2.,  3.,  4., -1., -1.])


In [39]:
x = torch.tensor([10, 20, 30])

print(x > 15)
print(x < 25)
print(x == 20)
print(x != 20)

a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])
c = torch.tensor([1, 2, 4])

print(torch.equal(a, b))
print(torch.equal(a, c))

tensor([False,  True,  True])
tensor([ True,  True, False])
tensor([False,  True, False])
tensor([ True, False,  True])
True
False


In [ ]:
x= torch.tensor([5,15,25,35,45])
print(torch.clamp(x, min=10, max=30)) #gives either below min. or above max

y= torch.tensor([2,3,4])
print(torch.prod(y))

z = torch.tensor([10.0, 20.0, 30.0])
print(z.var()) #var → variance
print(z.std()) #std → standard deviation

tensor([10, 15, 25, 30, 30])
tensor(24)
tensor(100.)
tensor(10.)


In [50]:
x = torch.tensor([3.0, 4.0])
print(torch.norm(x)) #pythagorous theorum

y = torch.tensor([1.0, 2.0, 3.0])
z = torch.tensor([4.0, 5.0, 6.0])

print(torch.dot(y, z))

A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])

print(A @ B)
print(torch.matmul(A, B))

tensor(5.)
tensor(32.)
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [54]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x.shape)

y = x.transpose(0, 1) #swap dimentions 0 and 1

print(y)
print(y.shape)

print(x.T)

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [58]:
x = torch.tensor([True, False, False])

print(x.any())
print(x.all())

y= torch.tensor([10,20,30])

print((y>15).any())
print((y>15).all())

tensor(True)
tensor(False)
tensor(True)
tensor(False)


In [59]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x.transpose(0, 1))
print(x.T)

condition = x > 3

print(condition)
print(condition.any())
print(condition.all())

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[False, False, False],
        [ True,  True,  True]])
tensor(True)
tensor(False)


In [65]:
x = torch.tensor([1, 2, 3, 4])

print(x.cumsum(dim=0)) #cumulative sum
print(x.cumprod(dim=0))


z = torch.tensor([2, 3, 4, 5])

print("prod:", z.prod())
print("cumsum:", z.cumsum(dim=0))
print("cumprod:", z.cumprod(dim=0))

tensor([ 1,  3,  6, 10])
tensor([ 1,  2,  6, 24])
prod: tensor(120)
cumsum: tensor([ 2,  5,  9, 14])
cumprod: tensor([  2,   6,  24, 120])


In [69]:
x= torch.tensor([1,2,3,4,5,6])

y= x.reshape(2,3)
print(x, y, sep='\n')

z= x.reshape(1,6)
print(z)

z1= x.reshape(6,1)
print(z1)

x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])

print(x.reshape(2, 4))
print(x.reshape(4, 2))
print(x.reshape(1, 8))

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])


In [71]:
x= torch.tensor([1,2,3,4])

y= x.view(2,2)

y[0,0]=100

print(y)
print(x)

x = torch.tensor([10, 20, 30, 40])

y = x.view(2, 2)

y[1, 0] = 99

print("y:")
print(y)

print("x:")
print(x)

tensor([[100,   2],
        [  3,   4]])
tensor([100,   2,   3,   4])
y:
tensor([[10, 20],
        [99, 40]])
x:
tensor([10, 20, 99, 40])


In [72]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x.shape)

y = x.flatten()

print(y)
print(y.shape)

torch.Size([2, 3])
tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])


In [76]:
x= torch.tensor([1,2,3])
print(x.shape)
print(x)

y= x.unsqueeze(0)

print(y)
print(y.shape)

x = torch.tensor([10, 20, 30])

a = x.unsqueeze(0)
b = x.unsqueeze(1)

print(a)
print(a.shape)

print(b)
print(b.shape)

torch.Size([3])
tensor([1, 2, 3])
tensor([[1, 2, 3]])
torch.Size([1, 3])
tensor([[10, 20, 30]])
torch.Size([1, 3])
tensor([[10],
        [20],
        [30]])
torch.Size([3, 1])


In [78]:
x = torch.zeros(2, 3, 4)
print(x.shape)

y = x.permute(2, 0, 1) # will change x to (4,2,3)
print(y)

torch.Size([2, 3, 4])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
