In [43]:
import torch

In [44]:
x= torch.tensor([10,20,30])
print(x.shape)
print(x.ndim,'\n')

y= torch.tensor([
    [10,20,30],
    [40,50,60]
])
print(y.shape)
print(y.ndim,'\n')

z= torch.tensor(10)
print(z.shape)
print(z.ndim, '\n')

print(len(y.shape)==y.ndim)

torch.Size([3])
1 

torch.Size([2, 3])
2 

torch.Size([])
0 

True


In [45]:
x=torch.zeros(2,3,4)
print(
    x,
    x.shape,
    x.ndim,
    x.numel(), #shows no. of elements
    sep='\n'
)

y=torch.zeros(2,3,4,5)
print(
    y.shape,
    y.ndim,
    y.numel(),
    sep='\n'
)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])
3
24
torch.Size([2, 3, 4, 5])
4
120


In [46]:
x= torch.tensor([
    [10,20,30],
    [40,50,60]
])
print(x.sum())
print(x.sum(dim=0))
print(x.sum(dim=1))

tensor(210)
tensor([50, 70, 90])
tensor([ 60, 150])


In [47]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original:")
print(x)
print(x.shape)

print("Sum dim=0:")
print(x.sum(dim=0))
print(x.sum(dim=0).shape)

print("Sum dim=1:")
print(x.sum(dim=1))
print(x.sum(dim=1).shape)

Original:
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
Sum dim=0:
tensor([5, 7, 9])
torch.Size([3])
Sum dim=1:
tensor([ 6, 15])
torch.Size([2])


In [48]:
x= torch.tensor([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(x.shape)
print(x.sum(dim=0))
print(x.sum(dim=1))
print(x.sum(dim=2), '\n')

print(x.sum(dim=-1))
print(x.sum(dim=-2))

print(torch.equal(
    x.sum(dim=2),
    x.sum(dim=-1)
))
print(torch.equal(
    x.sum(dim=1),
    x.sum(dim=-2)
))

torch.Size([2, 2, 3])
tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[ 5,  7,  9],
        [17, 19, 21]])
tensor([[ 6, 15],
        [24, 33]]) 

tensor([[ 6, 15],
        [24, 33]])
tensor([[ 5,  7,  9],
        [17, 19, 21]])
True
True


In [49]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x.shape, '\n')

y = x.sum(dim=1)
print(y)
print(y.shape,'\n')

z= x.sum(dim=1, keepdim=True)
print(z)
print(z.shape,'\n')

torch.Size([2, 3]) 

tensor([ 6, 15])
torch.Size([2]) 

tensor([[ 6],
        [15]])
torch.Size([2, 1]) 



In [50]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x.shape,'\n')

y = x.sum(dim=0)
print(y)
print(y.shape,'\n')

z= x.sum(dim=0, keepdim=True)
print(z)
print(z.shape,'\n')

torch.Size([2, 3]) 

tensor([5, 7, 9])
torch.Size([3]) 

tensor([[5, 7, 9]])
torch.Size([1, 3]) 



In [51]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x.shape,'\n')

print(x.sum(dim=0, keepdim=True))
print(x.sum(dim=0, keepdim=True).shape)

print(x.sum(dim=1, keepdim=True))
print(x.sum(dim=1, keepdim=True).shape)

torch.Size([2, 3]) 

tensor([[5, 7, 9]])
torch.Size([1, 3])
tensor([[ 6],
        [15]])
torch.Size([2, 1])
