In [2]:
import torch

In [2]:
x = torch.tensor(10)

print(type(x))
print(x)

<class 'torch.Tensor'>
tensor(10)


In [3]:
x1 = torch.tensor([10, 20, 30])
print(type(x1))
print(x1)

<class 'torch.Tensor'>
tensor([10, 20, 30])


In [4]:
x2 = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

print(type(x2))
print(x2)
print(x.dtype)
print(x.device)

<class 'torch.Tensor'>
tensor([[10, 20, 30],
        [40, 50, 60]])
torch.int64
cpu


In [5]:
a = 10
b = torch.tensor(10)
c = torch.tensor([10, 20, 30])

print(type(a))
print(type(b))
print(type(c))

print(b.ndim)
print(c.ndim)

print(b.shape)
print(c.shape)

<class 'int'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
0
1
torch.Size([])
torch.Size([3])


In [6]:
a1 = torch.tensor(10)
b1 = torch.tensor([10])
c1 = torch.tensor([10, 20, 30])
d1 = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

print(a1.ndim)
print(b1.ndim)
print(c1.ndim)
print(d1.ndim)

print(a1.shape)
print(b1.shape)
print(c1.shape)
print(d1.shape)

0
1
1
2
torch.Size([])
torch.Size([1])
torch.Size([3])
torch.Size([2, 3])


In [7]:
a2 = torch.tensor(10)
b2 = torch.tensor([10])
c2 = torch.tensor([[10]])

print(a2)
print(a2.ndim)
print(a2.shape, '\n')

print(b2)
print(b2.ndim)
print(b2.shape, '\n')

print(c2)
print(c2.ndim)
print(c2.shape)

tensor(10)
0
torch.Size([]) 

tensor([10])
1
torch.Size([1]) 

tensor([[10]])
2
torch.Size([1, 1])


In [8]:
vec = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(vec)
print(type(vec))
print(vec.dtype)
print(vec.ndim)
print(vec.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
<class 'torch.Tensor'>
torch.int64
3
torch.Size([2, 2, 2])


In [9]:
a3 = torch.tensor([1, 2, 3])
b3 = torch.zeros(3)
c3 = torch. ones(3)
d3 = torch.full((3,), 7)

print(a3)
print(b3)
print(c3)
print(d3)

print(a3.dtype)
print(b3.dtype)
print(c3.dtype)
print(d3.dtype)

tensor([1, 2, 3])
tensor([0., 0., 0.])
tensor([1., 1., 1.])
tensor([7, 7, 7])
torch.int64
torch.float32
torch.float32
torch.int64


In [10]:
x3 = torch.tensor(
    [1, 2, 3],
    dtype= torch.float32
)

print(x3)
print(x3.dtype, '\n')

y = torch.tensor([1, 2, 3])
print(y.shape)
print(y.dtype, '\n')

y1 = y.float()
print(y1)
print(y1.dtype, '\n')

y2 = y.to(torch.float32)
print(y2)
print(y2.dtype)

tensor([1., 2., 3.])
torch.float32 

torch.Size([3])
torch.int64 

tensor([1., 2., 3.])
torch.float32 

tensor([1., 2., 3.])
torch.float32


In [11]:
a4 = torch.tensor([1, 2, 3])
b4 = torch.tensor([1.0, 2.0, 3.0])
c4 = torch.tensor([1, 2, 3], dtype=torch.float32)

print(a4)
print(a4.dtype, '\n')

print(b4)
print(b4.dtype, '\n')

print(c4)
print(c4.dtype)

tensor([1, 2, 3])
torch.int64 

tensor([1., 2., 3.])
torch.float32 

tensor([1., 2., 3.])
torch.float32


In [12]:
x4 = torch.tensor([1, 2, 3])

print(x4)
print(x4.dtype, '\n')

y3 = x4.float()
print(y3)
print(y3.dtype, '\n')

y4 = x4.to(torch.float32)
print(y4)
print(y4.dtype, '\n')

x4 = x4.float()
print(x4)
print(x4.dtype, '\n')

x5 = torch.tensor([1.5, 2.7, 3.9])
print(x5)
print(x5.type, '\n')

y5 = x5.int()
print(y5)
print(y5.dtype, '\n')

x6 = torch.tensor([1, 2, 3], dtype=float)
print(x6, '\n')

y6 = torch.tensor([1.5, 2.6, 3.6], dtype=int)
print(y6)

tensor([1, 2, 3])
torch.int64 

tensor([1., 2., 3.])
torch.float32 

tensor([1., 2., 3.])
torch.float32 

tensor([1., 2., 3.])
torch.float32 

tensor([1.5000, 2.7000, 3.9000])
<built-in method type of Tensor object at 0x000001EB4A540D20> 

tensor([1, 2, 3], dtype=torch.int32)
torch.int32 

tensor([1., 2., 3.], dtype=torch.float64) 

tensor([1, 2, 3])


In [13]:
x7 = torch.tensor([1, 2, 3])

print(x7.int())
print(x7.long())
print(x7.float())
print(x7.double(), '\n')

print(x7.int().dtype)
print(x7.long().dtype)
print(x7.float().dtype)
print(x7.double().dtype)

tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64) 

torch.int32
torch.int64
torch.float32
torch.float64


In [14]:
y7 = torch.tensor([1.5, 2.8, 3.9])

print(y7)
print(y7.dtype, '\n')

a5 = y7.int()
b5 = y7.long()
c5 = y7.float()

print(a5)
print(a5.dtype, '\n')

print(b5)
print(b5.dtype, '\n')

print(c5)
print(c5.dtype, '\n')

print(y7)
print(y7.dtype, '\n')

tensor([1.5000, 2.8000, 3.9000])
torch.float32 

tensor([1, 2, 3], dtype=torch.int32)
torch.int32 

tensor([1, 2, 3])
torch.int64 

tensor([1.5000, 2.8000, 3.9000])
torch.float32 

tensor([1.5000, 2.8000, 3.9000])
torch.float32 



In [3]:
x8 = torch.tensor([1, 2, 3])
print(x8.device)

cpu


In [5]:
x9 = torch.tensor([1, 2, 3])
x9 = x9.to("cpu")
print(x9.device)

cpu


In [6]:
print(torch.cuda.is_available())

False


In [8]:
x10 = torch.tensor([1, 2, 3], device="cpu")
print(x10.device)

cpu


In [13]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

x10= x10.to("cpu")
print(x10.device)

cpu


In [16]:
x11 = torch.tensor([1, 2, 3])

print(x11.device)
print(torch.cuda.is_available())

y11 = x11.to("cpu")

print(y11)
print(y11.device)

cpu
False
tensor([1, 2, 3])
cpu


In [18]:
n = torch.zeros(3)
m = torch.zeros(2,3)

print(n)
print(n.shape)
print(n.dtype, '\n')

print(m)
print(m.shape)
print(m.dtype)

tensor([0., 0., 0.])
torch.Size([3])
torch.float32 

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
torch.float32


In [25]:
n1 = torch.ones(3)
m1 = torch.ones((2,2))
p1 = torch.ones(3, dtype=torch.int64)

print(n1)
print(n1.shape)
print(n1.dtype, '\n')

print(m1)
print(m1.shape)
print(m1.dtype, '\n')

print(p1)
print(p1.shape)
print(p1.dtype)

tensor([1., 1., 1.])
torch.Size([3])
torch.float32 

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])
torch.float32 

tensor([1, 1, 1])
torch.Size([3])
torch.int64


In [26]:
m2 = torch.full((4,), 7)
n2 = torch.full((2,2), 7, dtype=torch.float32)
p2 = torch.full((3,), 2.5)

print(n2)
print(n2.shape)
print(n2.dtype, '\n')

print(m2)
print(m2.shape)
print(m2.dtype, '\n')

print(p2)
print(p2.shape)
print(p2.dtype)

tensor([[7., 7.],
        [7., 7.]])
torch.Size([2, 2])
torch.float32 

tensor([7, 7, 7, 7])
torch.Size([4])
torch.int64 

tensor([2.5000, 2.5000, 2.5000])
torch.Size([3])
torch.float32


In [27]:
a = torch.full((5,), 10)
b = torch.full((2, 3), -1)
c = torch.full((4,), 2.5)

print(a)
print(a.dtype)

print(b)
print(b.dtype)

print(c)
print(c.dtype)

tensor([10, 10, 10, 10, 10])
torch.int64
tensor([[-1, -1, -1],
        [-1, -1, -1]])
torch.int64
tensor([2.5000, 2.5000, 2.5000, 2.5000])
torch.float32


In [28]:
a = torch.arange(5)
b = torch.arange(2, 8)
c = torch.arange(0, 10, 2)
d = torch.arange(10, 0, -2)
e = torch.arange(5, dtype=torch.float32)

print(a)
print(b)
print(c)
print(d)
print(e)
print(e.dtype)

tensor([0, 1, 2, 3, 4])
tensor([2, 3, 4, 5, 6, 7])
tensor([0, 2, 4, 6, 8])
tensor([10,  8,  6,  4,  2])
tensor([0., 1., 2., 3., 4.])
torch.float32


In [29]:
n = torch.linspace(0, 10, 6)
m = torch.linspace(-1, 1, 5)
o = torch.linspace(0, 1, 11)

print(n)
print(m)
print(o)

tensor([ 0.,  2.,  4.,  6.,  8., 10.])
tensor([-1.0000, -0.5000,  0.0000,  0.5000,  1.0000])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])


In [30]:
x = torch.rand(3)
y = torch.rand(2,3)

print(x)
print(x.shape)
print(x.dtype, '\n')

print(y)
print(y.shape)
print(y.dtype)

tensor([0.2460, 0.6158, 0.7171])
torch.Size([3])
torch.float32 

tensor([[0.4914, 0.6558, 0.5146],
        [0.8320, 0.3723, 0.1015]])
torch.Size([2, 3])
torch.float32
