In [98]:
import torch

In [99]:
x = torch.tensor(10)

print(type(x))
print(x)

<class 'torch.Tensor'>
tensor(10)


In [100]:
x1 = torch.tensor([10, 20, 30])
print(type(x1))
print(x1)

<class 'torch.Tensor'>
tensor([10, 20, 30])


In [101]:
x2 = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

print(type(x2))
print(x2)
print(x.dtype)
print(x.device)

<class 'torch.Tensor'>
tensor([[10, 20, 30],
        [40, 50, 60]])
torch.int64
cpu


In [102]:
a = 10
b = torch.tensor(10)
c = torch.tensor([10, 20, 30])

print(type(a))
print(type(b))
print(type(c))

print(b.ndim)
print(c.ndim)

print(b.shape)
print(c.shape)

<class 'int'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
0
1
torch.Size([])
torch.Size([3])


In [103]:
a1 = torch.tensor(10)
b1 = torch.tensor([10])
c1 = torch.tensor([10, 20, 30])
d1 = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

print(a1.ndim)
print(b1.ndim)
print(c1.ndim)
print(d1.ndim)

print(a1.shape)
print(b1.shape)
print(c1.shape)
print(d1.shape)

0
1
1
2
torch.Size([])
torch.Size([1])
torch.Size([3])
torch.Size([2, 3])


In [104]:
a2 = torch.tensor(10)
b2 = torch.tensor([10])
c2 = torch.tensor([[10]])

print(a2)
print(a2.ndim)
print(a2.shape, '\n')

print(b2)
print(b2.ndim)
print(b2.shape, '\n')

print(c2)
print(c2.ndim)
print(c2.shape)

tensor(10)
0
torch.Size([]) 

tensor([10])
1
torch.Size([1]) 

tensor([[10]])
2
torch.Size([1, 1])


In [105]:
vec = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(vec)
print(type(vec))
print(vec.dtype)
print(vec.ndim)
print(vec.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
<class 'torch.Tensor'>
torch.int64
3
torch.Size([2, 2, 2])


In [106]:
a3 = torch.tensor([1, 2, 3])
b3 = torch.zeros(3)
c3 = torch. ones(3)
d3 = torch.full((3,), 7)

print(a3)
print(b3)
print(c3)
print(d3)

print(a3.dtype)
print(b3.dtype)
print(c3.dtype)
print(d3.dtype)

tensor([1, 2, 3])
tensor([0., 0., 0.])
tensor([1., 1., 1.])
tensor([7, 7, 7])
torch.int64
torch.float32
torch.float32
torch.int64


In [107]:
x3 = torch.tensor(
    [1, 2, 3],
    dtype= torch.float32
)

print(x3)
print(x3.dtype, '\n')

y = torch.tensor([1, 2, 3])
print(y.shape)
print(y.dtype, '\n')

y1 = y.float()
print(y1)
print(y1.dtype, '\n')

y2 = y.to(torch.float32)
print(y2)
print(y2.dtype)

tensor([1., 2., 3.])
torch.float32 

torch.Size([3])
torch.int64 

tensor([1., 2., 3.])
torch.float32 

tensor([1., 2., 3.])
torch.float32


In [108]:
a4 = torch.tensor([1, 2, 3])
b4 = torch.tensor([1.0, 2.0, 3.0])
c4 = torch.tensor([1, 2, 3], dtype=torch.float32)

print(a4)
print(a4.dtype, '\n')

print(b4)
print(b4.dtype, '\n')

print(c4)
print(c4.dtype)

tensor([1, 2, 3])
torch.int64 

tensor([1., 2., 3.])
torch.float32 

tensor([1., 2., 3.])
torch.float32


In [109]:
x4 = torch.tensor([1, 2, 3])

print(x4)
print(x4.dtype, '\n')

y3 = x4.float()
print(y3)
print(y3.dtype, '\n')

y4 = x4.to(torch.float32)
print(y4)
print(y4.dtype, '\n')

x4 = x4.float()
print(x4)
print(x4.dtype, '\n')

x5 = torch.tensor([1.5, 2.7, 3.9])
print(x5)
print(x5.type, '\n')

y5 = x5.int()
print(y5)
print(y5.dtype, '\n')

x6 = torch.tensor([1, 2, 3], dtype=float)
print(x6, '\n')

y6 = torch.tensor([1.5, 2.6, 3.6], dtype=int)
print(y6)

tensor([1, 2, 3])
torch.int64 

tensor([1., 2., 3.])
torch.float32 

tensor([1., 2., 3.])
torch.float32 

tensor([1., 2., 3.])
torch.float32 

tensor([1.5000, 2.7000, 3.9000])
<built-in method type of Tensor object at 0x0000015591C7E760> 

tensor([1, 2, 3], dtype=torch.int32)
torch.int32 

tensor([1., 2., 3.], dtype=torch.float64) 

tensor([1, 2, 3])


In [110]:
x7 = torch.tensor([1, 2, 3])

print(x7.int())
print(x7.long())
print(x7.float())
print(x7.double(), '\n')

print(x7.int().dtype)
print(x7.long().dtype)
print(x7.float().dtype)
print(x7.double().dtype)

tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64) 

torch.int32
torch.int64
torch.float32
torch.float64


In [111]:
y7 = torch.tensor([1.5, 2.8, 3.9])

print(y7)
print(y7.dtype, '\n')

a5 = y7.int()
b5 = y7.long()
c5 = y7.float()

print(a5)
print(a5.dtype, '\n')

print(b5)
print(b5.dtype, '\n')

print(c5)
print(c5.dtype, '\n')

print(y7)
print(y7.dtype, '\n')

tensor([1.5000, 2.8000, 3.9000])
torch.float32 

tensor([1, 2, 3], dtype=torch.int32)
torch.int32 

tensor([1, 2, 3])
torch.int64 

tensor([1.5000, 2.8000, 3.9000])
torch.float32 

tensor([1.5000, 2.8000, 3.9000])
torch.float32 

