In [47]:
import pandas as pd
import numpy as np

In [48]:
data2 = [
    ['ayush', 22, 'delhi'],
    ['rahul', 24, 'mumbai'],
    ['aman', 21, 'jaipur']
]

df = pd.DataFrame(data2, columns=['name', 'age', 'city'])
print(df)

    name  age    city
0  ayush   22   delhi
1  rahul   24  mumbai
2   aman   21  jaipur


In [49]:
data = {
    'name': ['rahul', 'aman', 'priya'],
    'age': [22, 25, 24],
    'salary': [40000, 55000,50000]
}

df = pd.DataFrame(data)
print(
    data,
    df,
    df['name'],
    df['age'],
    df.shape,
    df.columns,
    df.index,
    df.dtypes,
    df.head(2),
    df.tail(2),
    df.info(),
    df.describe(),
    sep='\n'
)

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str  
 1   age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes
{'name': ['rahul', 'aman', 'priya'], 'age': [22, 25, 24], 'salary': [40000, 55000, 50000]}
    name  age  salary
0  rahul   22   40000
1   aman   25   55000
2  priya   24   50000
0    rahul
1     aman
2    priya
Name: name, dtype: str
0    22
1    25
2    24
Name: age, dtype: int64
(3, 3)
Index(['name', 'age', 'salary'], dtype='str')
RangeIndex(start=0, stop=3, step=1)
name        str
age       int64
salary    int64
dtype: object
    name  age  salary
0  rahul   22   40000
1   aman   25   55000
    name  age  salary
1   aman   25   55000
2  priya   24   50000
None
             age        salary
count   3.000000      3.000000
mean   23.666667  48333.333333
std     1.527525   76

In [50]:
data = {
    'name': ['ayush','rahul','aman'],
    'age' : [22, 24, 21],
    'city': ['delhi', 'mumbai', 'jaipur']
}

df1 = pd.DataFrame(data)
print(
    df1,
    df1.shape,
    df1.columns,
    df1.dtypes,
    df.head(2),
    sep='\n'
)

    name  age    city
0  ayush   22   delhi
1  rahul   24  mumbai
2   aman   21  jaipur
(3, 3)
Index(['name', 'age', 'city'], dtype='str')
name      str
age     int64
city      str
dtype: object
    name  age  salary
0  rahul   22   40000
1   aman   25   55000


In [51]:
s1 = pd.Series(['ayush', 'rahul', 'aman'])
s2 = pd.Series([22, 24, 21])

df3 = pd.DataFrame({
    'names': s1,
    'ages': s2
})

print(
    s1,
    s2,
    df3,
    sep='\n'
)

0    ayush
1    rahul
2     aman
dtype: str
0    22
1    24
2    21
dtype: int64
   names  ages
0  ayush    22
1  rahul    24
2   aman    21


In [52]:
data4 = [
    {"name": "ayush", "age": 22, "city": "delhi"},
    {"name": "rahul", "age": 24, "city": "mumbai"},
    {"name": "aman", "age": 21, "city": "jaipur"}
]

df4 = pd.DataFrame(data)

print(df4)

    name  age    city
0  ayush   22   delhi
1  rahul   24  mumbai
2   aman   21  jaipur


In [53]:
arr = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

df5 = pd.DataFrame(
    arr,
    columns= ['a', 'b']
)

print(df5)

    a   b
0  10  20
1  30  40
2  50  60


In [54]:
s1 =  pd.Series([10, 20, 30])

df6 = pd.DataFrame(s1)

print(s1, '\n', df6)

0    10
1    20
2    30
dtype: int64 
     0
0  10
1  20
2  30


In [55]:
data2 = [
    ['ayush', 22],
    ['rahul', 25],
    ['aman', 24]
]

df7 = pd.DataFrame(
    data,
    columns= ['name', 'age'],
    index= ['a', 'b', 'c']
)

print(
    data2,
    df7,
    df7.loc['b'],
    sep= '\n'
)



[['ayush', 22], ['rahul', 25], ['aman', 24]]
    name  age
a  ayush   22
b  rahul   24
c   aman   21
name    rahul
age        24
Name: b, dtype: object


In [56]:
df8 = pd.DataFrame()
print(df8)

df9 = pd.DataFrame(columns= ['name', 'age', 'city'])
print(df9)

Empty DataFrame
Columns: []
Index: []
Empty DataFrame
Columns: [name, age, city]
Index: []


In [57]:
data5 = np.zeros((3,4))
df9 =pd.DataFrame(data5)
print(data5, '\n', df9)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
      0    1    2    3
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
