In [30]:
import numpy as np

In [31]:
A= np.array([
    [1,2],
    [3,4]
])

B= np.array([
    [5,6],
    [7,8]
])

print(A*B) #element wise multiplication
print(A@B) #matrix multiplication
print(np.matmul(A,B)) #matrix multiplication
print(np.dot(A,B)) 

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [32]:
A1= np.array([
    [1,2,3],
    [4,5,6]
])

B1= np.array([
    [10,20],
    [30,40],
    [50,60]
])

print(A1@B1)

[[220 280]
 [490 640]]


In [33]:
A2= np.array([
    [1,2,3],
    [4,5,6]
])
B2=A2.T #transpose

print(A2, B2, sep='\n')
#print(A2*B2) not possible
print(A2@A2.T)
print(A2@B2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


In [34]:
A3= np.array([
    [1,2],
    [3,4]
])

A3_inv=np.linalg.inv(A3) #inverse
print(A3_inv)

I= A3@A3_inv
print(I)

A3_det= np.linalg.det(A3) #determinant= det(A) = (a × d) - (b × c)
print(A3_det)

A3_eig= np.linalg.eig(A3)
print(A3_eig)

A3_values, A3_vectors= np.linalg.eig(A3)
print(A3_values, A3_vectors, sep='\n')

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [35]:
A4 = np.array([
    [3, 0],
    [0, 2]
])

values, vectors = np.linalg.eig(A4)

print(values)
print(vectors)

[3. 2.]
[[1. 0.]
 [0. 1.]]


In [36]:
A5= np.array([
    [2,0],
    [0,5]
])

values, vectors= np.linalg.eig(A5)
print(values, vectors, sep='\n')

[2. 5.]
[[1. 0.]
 [0. 1.]]


In [37]:
#equation
#2x + y = 5
#x + 3y = 6

A6= np.array([
    [2,1],
    [1,3]
])

b= np.array([5,6])

x= np.linalg.solve(A6, b) #np.linalg.inv(A6) @ b
print(x)


A7= np.array([
    [1,1],
    [1,-1]
])

b1= np.array([10,2])

x1= np.linalg.solve(A7, b1)
print(x1)

[1.8 1.4]
[6. 4.]


In [38]:
A= np.array([
    [1,2],
    [3,4]
])

B= np.array([
    [5,6],
    [7,8]
])

print(A*B)
print(A@B)

A1= np.array([
    [2,3],
    [1,4]
])

A1_inv= np.linalg.inv(A1)
print(A1_inv)

values, vectors= np.linalg.eig(A1)
print(values, vectors, sep='\n')

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[ 0.8 -0.6]
 [-0.2  0.4]]
[1. 5.]
[[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]
