In [16]:
import numpy as np

In [17]:
A= np.array([
    [1,2],
    [3,4]
])

B= np.array([
    [5,6],
    [7,8]
])

print(A*B) #element wise multiplication
print(A@B) #matrix multiplication
print(np.matmul(A,B)) #matrix multiplication
print(np.dot(A,B)) 

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [18]:
A1= np.array([
    [1,2,3],
    [4,5,6]
])

B1= np.array([
    [10,20],
    [30,40],
    [50,60]
])

print(A1@B1)

[[220 280]
 [490 640]]


In [19]:
A2= np.array([
    [1,2,3],
    [4,5,6]
])
B2=A2.T #transpose

print(A2, B2, sep='\n')
#print(A2*B2) not possible
print(A2@A2.T)
print(A2@B2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


In [21]:
A3= np.array([
    [1,2],
    [3,4]
])

A3_inv=np.linalg.inv(A3)