In [1]:
import numpy as np

In [6]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

arr2 = np.array([10,20,30])
print( arr1, arr2)
print(arr1+arr2, '\n')
print(arr2+arr1)

[[1 2 3]
 [4 5 6]] [10 20 30]
[[11 22 33]
 [14 25 36]] 

[[11 22 33]
 [14 25 36]]


In [7]:
a = np.array([
    [1],
    [2],
    [3]
])

b = np.array([10,20,30])

print(a+b, b+a, sep='\n')

[[11 21 31]
 [12 22 32]
 [13 23 33]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
