In [1]:
import numpy as np

In [ ]:
a= np.array([10,20,30,40,50])
np.save("data.npy", a)

In [4]:
b= np.load("data.npy")
print(b)

[10 20 30 40 50]


In [ ]:
a1= np.array([10,20,30,40,50])
np.savetxt("data.txt", a1)

In [8]:
b1= np.loadtxt("data.txt")
print(b1)

[10. 20. 30. 40. 50.]


In [10]:
a = np.array([
    [1, 2],
    [3, 4]
])

np.save("matrix.npy", a)

b= np.load("matrix.npy")
print(b)

[[1 2]
 [3 4]]


In [11]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.int32)

np.save("data.npy", a)

b = np.load("data.npy")

print(b)
print(b.shape)
print(b.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
int32


In [24]:
a= np.array([1,2,3])
b= np.array([10,20,30])

np.savez("data.npz", arr1=a, arr2=b)

data= np.load("data.npz")
print(data,
    data["arr1"],
    data["arr2"],
    sep='\n'
)

NpzFile 'data.npz' with keys: arr1, arr2
[1 2 3]
[10 20 30]


In [44]:
a= np.array([1,2,3])
b= np.array([11,22,33])

np.savez("data.npz", a, b)

data1= np.load("data.npz")

print(data1)

a_loaded= data1["arr_0"]
b_loaded= data1["arr_1"]

print(
    a_loaded,
    b_loaded,
    sep='\n'
)

NpzFile 'data.npz' with keys: arr_0, arr_1
[1 2 3]
[11 22 33]


In [54]:
np.savetxt("data.csv", a, delimiter=",")
a= np.loadtxt("data.csv", delimiter=",")

print(a)

[1. 2. 3.]


In [65]:
names = np.array(["Ayush", "Rahul", "Aman"])
ages = np.array([22, 24, 21])
marks = np.array([85, 90, 78])

data= np.column_stack((names, ages, marks))

np.savetxt("students.csv", data, delimiter=",", fmt="%s")

student= np.loadtxt("students.csv", delimiter=",", dtype=str)
print(student)

names_loaded= student[:,0]
ages_loaded= student[:,1].astype(int)
marks_loaded= student[:,2].astype(np.int32)

print(names_loaded)
print(ages_loaded.dtype)
print(marks_loaded.dtype)

[['Ayush' '22' '85']
 ['Rahul' '24' '90']
 ['Aman' '21' '78']]
['Ayush' 'Rahul' 'Aman']
int64
int32
