In [1]:
import numpy as np

In [2]:
a= np.array([
    [1,2,3],
    [4,5,6]
])
print(a.ndim, a.shape, a.size, sep='\n')

2
(2, 3)
6


In [3]:
print(a.reshape(2, -1))

[[1 2 3]
 [4 5 6]]


In [4]:
arr1= np.array([2,4,6,8])
print(arr1*3)

[ 6 12 18 24]


In [5]:
arr2= np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr2[1:,0:2])

[[40 50]
 [70 80]]


In [6]:
arr3= np.arange(1,13)
arr8= arr3.reshape(3,4)
print(arr8)
print(arr8[:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 3  7 11]


In [7]:
arr4= np.arange(1,10,2)
print(arr4)

[1 3 5 7 9]


In [8]:
arr5= np.array([10,20,30,40,50])
print(arr5[arr5>25])

print(
    np.mean(arr5),
    np.argmax(arr5),
    np.cumsum(arr5)
)

print(np.where(arr5>=30,1,0))

[30 40 50]
30.0 4 [ 10  30  60 100 150]
[0 0 1 1 1]


In [9]:
arr6=np.array([
    [1,2],
    [3,4]
])
arr7=np.array([
    [5,6],
    [7,8]
])
print(np.concatenate((arr6,arr7)))
print(np.stack((arr6, arr7), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [10]:
arr9= np.array([
    [10,20,30],
    [40,50,60]
])

print(
    np.sum(arr9, axis=0),
    np.sum(arr9, axis=1),
    sep='\n'
)

[50 70 90]
[ 60 150]


In [11]:
arr10= np.arange(5,51,5)
print(arr10)

[ 5 10 15 20 25 30 35 40 45 50]


In [12]:
arr11= np.arange(1,21).reshape(4,5)
print(arr11[1:3,1:4])

[[ 7  8  9]
 [12 13 14]]


In [13]:
marks = np.array([35, 72, 48, 91, 63, 27, 84])
print(marks[(marks>50) & (marks<90)])

[72 63 84]


In [14]:
print(np.where(marks>=40,1,0))

[0 1 1 1 1 0 1]


In [15]:
scores = np.array([45, 67, 89, 32, 76, 91, 54])
print(
    np.mean(scores),
    np.median(scores),
    np.min(scores),
    np.max(scores),
    np.argmax(scores),
    np.std(scores)
)

64.85714285714286 67.0 32 91 5 20.65656983990857


In [16]:
arr11 = np.array([1, 2, 3, 4, 5])
arr11 = np.insert(arr11, 2, 99)
arr11 = np.append(arr11, 100)
print(arr11)

[  1   2  99   3   4   5 100]


In [17]:
prices= np.array([
    [100, 200, 300],
    [150, 250, 350],
    [120, 220, 320]
])

tax= np.array([10, 20, 30])

new_price= prices+ tax
print(new_price)

[[110 220 330]
 [160 270 380]
 [130 240 350]]


In [18]:
X = np.array([
    [20, 50000],
    [25, 60000],
    [30, 75000],
    [35, 90000],
    [40, 120000]
])

print(X[X[:, 1]>70000])

[[    30  75000]
 [    35  90000]
 [    40 120000]]


In [19]:
print(np.mean(X[0:,0:1]))
print(np.mean(X[0:,1:]))
print(np.mean(X, axis=0))
print(np.mean(X, axis=1))

30.0
79000.0
[3.0e+01 7.9e+04]
[25010.  30012.5 37515.  45017.5 60020. ]


In [20]:
X = np.array([
    [10, 100],
    [20, 200],
    [30, 300]
])

feature_means= np.mean(X, axis=0)
centered_X= X-feature_means

print(feature_means)
print(centered_X)

[ 20. 200.]
[[ -10. -100.]
 [   0.    0.]
 [  10.  100.]]


In [21]:
data = np.array([
    [10, 20, 30, 40],
    [15, 25, 35, 45],
    [20, 30, 40, 50],
    [25, 35, 45, 55]
])

print(
    np.shape(data),
    np.mean(data, axis=0),
    np.max(data, axis=0),
    data[data[:,3]>45],
    data-np.mean(data, axis=0),
    np.std(data, axis=0),
    sep='\n'
)

(4, 4)
[17.5 27.5 37.5 47.5]
[25 35 45 55]
[[20 30 40 50]
 [25 35 45 55]]
[[-7.5 -7.5 -7.5 -7.5]
 [-2.5 -2.5 -2.5 -2.5]
 [ 2.5  2.5  2.5  2.5]
 [ 7.5  7.5  7.5  7.5]]
[5.59016994 5.59016994 5.59016994 5.59016994]


In [22]:
X = np.array([
    [10, 100, 1],
    [20, 200, 2],
    [30, 300, 3],
    [40, 400, 4],
    [50, 500, 5]
])

m= np.mean(X, axis=0)
s= np.std(X, axis=0)
z= (X-m)/s
print(
    m,
    s,
    z,
    np.mean(z, axis=0),
    np.std(z, axis=0),
    sep='\n'
)

[ 30. 300.   3.]
[ 14.14213562 141.42135624   1.41421356]
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
[0. 0. 0.]
[1. 1. 1.]


In [23]:
a = np.array([2, 4, 6])
print(a * 3)

[ 6 12 18]


In [24]:
print(
    np.arange(2, 12, 3),
    np.linspace(0, 10, 5)
)

[ 2  5  8 11] [ 0.   2.5  5.   7.5 10. ]


In [25]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(
    a.ndim,
    a.shape,
    a.size,
    a.dtype
)

2 (3, 3) 9 int64


In [26]:
a = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(
    a[1, 2],
    a[:, 1],
    a[0:2, 1:3],
    sep= '\n'
)

70
[ 20  60 100]
[[20 30]
 [60 70]]


In [27]:
a = np.arange(1, 13).reshape(3,4)

print(a)
print(a.reshape(3, -1))
print(a.reshape(-1))
print(a.flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(
    np.concatenate((a, b)),
    np.vstack((a, b)),
    np.hstack((a, b)),
    np.insert(a, 1, 99),
    np.delete(b, 0),
    sep= '\n'
)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[ 1 99  2  3]
[5 6]


In [29]:
a = np.arange(1, 13)
b = a.reshape(3, 4)

print(b.shape)
print(b[1:, 1:3])

(3, 4)
[[ 6  7]
 [10 11]]


In [30]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print(
    np.concatenate((a,b), axis=0),
    np.concatenate((a,b), axis=1),
    np.concatenate((b,a), axis=0),
    np.concatenate((b,a), axis=1),
    np.stack((a, b)),
    sep='\n'
)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[5 6]
 [7 8]
 [1 2]
 [3 4]]
[[5 6 1 2]
 [7 8 3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
