In [12]:
import numpy as np

In [13]:
a= np.array([
    [1,2,3],
    [4,5,6]
])
print(a.ndim, a.shape, a.size, sep='\n')

2
(2, 3)
6


In [14]:
print(a.reshape(2, -1))

[[1 2 3]
 [4 5 6]]


In [15]:
arr1= np.array([2,4,6,8])
print(arr1*3)

[ 6 12 18 24]


In [16]:
arr2= np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr2[1:,0:2])

[[40 50]
 [70 80]]


In [17]:
arr3= np.arange(1,13)
arr8= arr3.reshape(3,4)
print(arr8)
print(arr8[:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 3  7 11]


In [18]:
arr4= np.arange(1,10,2)
print(arr4)

[1 3 5 7 9]


In [19]:
arr5= np.array([10,20,30,40,50])
print(arr5[arr5>25])

print(
    np.mean(arr5),
    np.argmax(arr5),
    np.cumsum(arr5)
)

print(np.where(arr5>=30,1,0))

[30 40 50]
30.0 4 [ 10  30  60 100 150]
[0 0 1 1 1]


In [20]:
arr6=np.array([
    [1,2],
    [3,4]
])
arr7=np.array([
    [5,6],
    [7,8]
])
print(np.concatenate((arr6,arr7)))
print(np.stack((arr6, arr7), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [21]:
arr9= np.array([
    [10,20,30],
    [40,50,60]
])

print(
    np.sum(arr9, axis=0),
    np.sum(arr9, axis=1),
    sep='\n'
)

[50 70 90]
[ 60 150]


In [22]:
arr10= np.arange(5,51,5)
print(arr10)

[ 5 10 15 20 25 30 35 40 45 50]


In [23]:
arr11= np.arange(1,21).reshape(4,5)
print(arr11[1:3,1:4])

[[ 7  8  9]
 [12 13 14]]


In [24]:
marks = np.array([35, 72, 48, 91, 63, 27, 84])
print(marks[(marks>50) & (marks<90)])

[72 63 84]


In [25]:
print(np.where(marks>=40,1,0))

[0 1 1 1 1 0 1]


In [26]:
scores = np.array([45, 67, 89, 32, 76, 91, 54])
print(
    np.mean(scores),
    np.median(scores),
    np.min(scores),
    np.max(scores),
    np.argmax(scores),
    np.std(scores)
)

64.85714285714286 67.0 32 91 5 20.65656983990857


In [27]:
arr11 = np.array([1, 2, 3, 4, 5])
arr11 = np.insert(arr11, 2, 99)
arr11 = np.append(arr11, 100)
print(arr11)

[  1   2  99   3   4   5 100]


In [28]:
prices= np.array([
    [100, 200, 300],
    [150, 250, 350],
    [120, 220, 320]
])

tax= np.array([10, 20, 30])

new_price= prices+ tax
print(new_price)

[[110 220 330]
 [160 270 380]
 [130 240 350]]
