In [1]:
import numpy as np

In [2]:
a= np.array([
    [1,2,3],
    [4,5,6]
])
print(a.ndim, a.shape, a.size, sep='\n')

2
(2, 3)
6


In [3]:
print(a.reshape(2, -1))

[[1 2 3]
 [4 5 6]]


In [4]:
arr1= np.array([2,4,6,8])
print(arr1*3)

[ 6 12 18 24]


In [5]:
arr2= np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr2[1:,0:2])

[[40 50]
 [70 80]]


In [ ]:
arr3= np.arange(1,13)
arr8= arr3.reshape(3,4)
print(arr8)
print(arr8[:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 3  7 11]


In [8]:
arr4= np.arange(1,10,2)
print(arr4)

[1 3 5 7 9]


In [13]:
arr5= np.array([10,20,30,40,50])
print(arr5[arr5>25])

print(
    np.mean(arr5),
    np.argmax(arr5),
    np.cumsum(arr5)
)

print(np.where(arr5>=30,1,0))

[30 40 50]
30.0 4 [ 10  30  60 100 150]
[0 0 1 1 1]


In [18]:
arr6=np.array([
    [1,2],
    [3,4]
])
arr7=np.array([
    [5,6],
    [7,8]
])
print(np.concatenate((arr6,arr7)))
print(np.stack((arr6, arr7), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [21]:
arr9= np.array([
    [10,20,30],
    [40,50,60]
])

print(
    np.sum(arr9, axis=0),
    np.sum(arr9, axis=1),
    sep='\n'
)

[50 70 90]
[ 60 150]
