In [4]:
import numpy as np

In [ ]:
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(2, 3))
print(np.random.randint(1,10))
print(np.random.randint(1,10, 5))
print(np.random.randint(1,10, (2,3)))
print(np.random.random(5))
print(np.random.randn(5)) #mean=0, std=1
print(np.random.normal(100, 15, 5)) #mean=100, std=15, 5 values
print(np.random.seed(42))

a = np.array([10, 20, 30, 40, 50])
np.random.choice(a)

0.5412689037203295
[0.7793272  0.9048177  0.94627453 0.47042318 0.75030553]
[[0.8623386  0.56184529 0.48086601]
 [0.67387107 0.58573109 0.55123394]]
4
[2 2 1 9 4]
[[3 8 7]
 [3 8 1]]
[0.98882464 0.4240144  0.59198347 0.9684889  0.9291046 ]
[-0.93546456  0.50190297 -0.4535762  -1.79350278  0.19636351]
[ 85.88754379  93.10354273 116.39530924  82.89021327  71.90646546]
None


np.int64(40)

In [19]:
a= np.array([10, 20, 30, 40, 50])

print(
    np.random.rand(),
    np.random.rand(7),
    np.random.rand(3,2),
    np.random.randint(1, 10, 5),
    np.random.randint(1, 20, (3,3)),
    np.random.randn(5),
    np.random.random(5),
    np.random.normal(100, 15, 5), #mean, std, no. of values
    np.random.choice(a, 7),
    np.random.choice(a, 3, replace= False),# cannot repeat values
    sep='\n'
)

np.random.seed(10)
print(np.random.randint(1, 100, 5))

np.random.shuffle(a)
print("a=", a)

c= np.random.permutation(a)
print("c=", c)

rng= np.random.default_rng(42)
print(rng.random(3))

0.08833981417401027
[0.68535982 0.95339335 0.00394827 0.51219226 0.81262096 0.61252607
 0.72175532]
[[0.29187607 0.91777412]
 [0.71457578 0.54254437]
 [0.14217005 0.37334076]]
[7 2 5 3 7]
[[12 11 10]
 [16 19 17]
 [ 8 12 18]]
[ 0.1327083  -0.47614201  1.30847308  0.19501328  0.40020999]
[0.35165264 0.75464769 0.29596171 0.88393648 0.32551164]
[94.93551494 94.56622321 83.06303124 94.75434286 84.2091022 ]
[10 20 20 50 10 30 20]
[10 50 30]
[10 16 65 29 90]
a= [30 50 40 20 10]
c= [20 40 10 50 30]
[0.77395605 0.43887844 0.85859792]
