In [1]:
import numpy as np

In [2]:
a = np.array([2, 4, 6])
print(a * 3)

[ 6 12 18]


In [4]:
print(
    np.arange(2, 12, 3),
    np.linspace(0, 10, 5)
)

[ 2  5  8 11] [ 0.   2.5  5.   7.5 10. ]


In [6]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(
    a.ndim,
    a.shape,
    a.size,
    a.dtype
)

2 (3, 3) 9 int64


In [9]:
a = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(
    a[1, 2],
    a[:, 1],
    a[0:2, 1:3],
    sep= '\n'
)

70
[ 20  60 100]
[[20 30]
 [60 70]]


In [14]:
a = np.arange(1, 13).reshape(3,4)

print(a)
print(a.reshape(3, -1))
print(a.reshape(-1))
print(a.flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(
    np.concatenate((a, b)),
    np.vstack((a, b)),
    np.hstack((a, b)),
    np.insert(a, 1, 99),
    np.delete(b, 0),
    sep= '\n'
)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[ 1 99  2  3]
[5 6]


In [22]:
a = np.arange(1, 13)
b = a.reshape(3, 4)

print(b.shape)
print(b[1:, 1:3])

(3, 4)
[[ 6  7]
 [10 11]]


In [25]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

print(
    np.concatenate((a,b), axis=0),
    np.concatenate((a,b), axis=1),
    np.concatenate((b,a), axis=0),
    np.concatenate((b,a), axis=1),
    np.stack((a, b)),
    sep='\n'
)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[5 6]
 [7 8]
 [1 2]
 [3 4]]
[[5 6 1 2]
 [7 8 3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
