In [1]:
import numpy as np

In [5]:
a = np.array([40, 10, 30, 20, 50])
b= np.sort(a)
print(np.sort(a))
print(b)

print(np.sort(a)[::-1])
print(np.argsort(a))

[10 20 30 40 50]
[10 20 30 40 50]
[50 40 30 20 10]
[1 3 2 0 4]


In [11]:
names= np.array(["A", "B", "C", "D"])
scores= np.array([80, 50, 90, 70])

idx= np.argsort(scores)
print(idx)

print(names[idx])

[1 3 0 2]
['B' 'D' 'A' 'C']


In [ ]:
a= np.array([
    [30, 10, 20],
    [60, 40, 50]
])

print(np.sort(a))
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

[[10 20 30]
 [40 50 60]]
[[30 10 20]
 [60 40 50]]
[[10 20 30]
 [40 50 60]]


In [16]:
a2 = np.array([
    [30, 50, 10],
    [20, 40, 60]
])
print(np.sort(a2))
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[10 30 50]
 [20 40 60]]
[[20 40 10]
 [30 50 60]]
[[10 30 50]
 [20 40 60]]


In [36]:
a3 = np.array([10, 20, 30, 40, 50])
print(np.searchsorted(a3, 25))

a4 = np.array([30, 50, 90, 10, 20])
print(np.searchsorted(a4, 20))

print(np.searchsorted(a3, [5, 25, 15]))
print(np.searchsorted(a4, [5, 35, 15]))

a5 = np.array([10, 20, 20, 20, 30])
print(np.searchsorted(a5, 20, side="left"))
print(np.searchsorted(a5, 20, side="right"))
print(np.searchsorted(a5, 15, side="left"))

2
0
[0 2 1]
[0 1 0]
1
4
1


In [39]:
a6= np.array([10, 20, 30, 40, 50])
print(np.where(a6>25))
print(a6[np.where(a6>25)])

(array([2, 3, 4]),)
[30 40 50]


In [43]:
a7 = np.array([0, 10, 0, 20, 30, 0])
print(np.nonzero(a7))

a8 = np.array([
    [0, 5, 0],
    [2, 0, 7]
])
print(np.nonzero(a8))

(array([1, 3, 4]),)
(array([0, 1, 1]), array([1, 0, 2]))


In [44]:
a9 = np.array([10, 50, 20, 80, 30])
print(np.argmin(a9))
print(np.argmax(a9))

0
3


In [46]:
a10 = np.array([40, 10, 30, 20])
print(np.argsort(a10))
print(np.argsort(a10)[::-1])

[1 3 2 0]
[0 2 3 1]
