In [1]:
import numpy as np

In [5]:
a = np.array([40, 10, 30, 20, 50])
b= np.sort(a)
print(np.sort(a))
print(b)

print(np.sort(a)[::-1])
print(np.argsort(a))

[10 20 30 40 50]
[10 20 30 40 50]
[50 40 30 20 10]
[1 3 2 0 4]


In [11]:
names= np.array(["A", "B", "C", "D"])
scores= np.array([80, 50, 90, 70])

idx= np.argsort(scores)
print(idx)

print(names[idx])

[1 3 0 2]
['B' 'D' 'A' 'C']


In [ ]:
a= np.array([
    [30, 10, 20],
    [60, 40, 50]
])

print(np.sort(a))
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

[[10 20 30]
 [40 50 60]]
[[30 10 20]
 [60 40 50]]
[[10 20 30]
 [40 50 60]]


In [16]:
a2 = np.array([
    [30, 50, 10],
    [20, 40, 60]
])
print(np.sort(a2))
print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[10 30 50]
 [20 40 60]]
[[20 40 10]
 [30 50 60]]
[[10 30 50]
 [20 40 60]]
